Format generated sarif.rs using prettyplease instead of rustfmt
This avoids relying on the user's host to have a suitable version of
rustfmt installed for the right toolchain.

    error: failed to run custom build command for `serde-sarif v0.3.0`

    Caused by:
      process didn't exit successfully: `target/debug/build/serde-sarif-c0dd8a6b8827cf78/build-script-build` (exit status: 1)
      --- stdout
      cargo:rerun-if-changed=src/schema.json

      --- stderr
      error: 'rustfmt' is not installed for the toolchain '1.58.0-x86_64-unknown-linux-gnu'
      To install, run `rustup component add rustfmt --toolchain 1.58.0-x86_64-unknown-linux-gnu`
      Error: Broken pipe (os error 32)